#############################################################################
# Makefile for building: AutoRPG
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Apr 24 10:47:26 2013
# Project:  AutoRPG.pro
# Template: app
# Command: /home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile AutoRPG.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -I. -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtGui -L/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		autorpg.cpp \
		newcharacter.cpp \
		character.cpp \
		namegenerator.cpp \
		game.cpp \
		item.cpp \
		creature.cpp \
		eventsgenerator.cpp moc_autorpg.cpp \
		moc_newcharacter.cpp \
		moc_game.cpp \
		moc_eventsgenerator.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		autorpg.o \
		newcharacter.o \
		character.o \
		namegenerator.o \
		game.o \
		item.o \
		creature.o \
		eventsgenerator.o \
		moc_autorpg.o \
		moc_newcharacter.o \
		moc_game.o \
		moc_eventsgenerator.o \
		qrc_res.o
DIST          = ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		AutoRPG.pro
QMAKE_TARGET  = AutoRPG
DESTDIR       = 
TARGET        = AutoRPG

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_autorpg.h ui_newcharacter.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: AutoRPG.pro  ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++/qmake.conf ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl \
		/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile AutoRPG.pro
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl:
/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile AutoRPG.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/AutoRPG1.0.0 || $(MKDIR) .tmp/AutoRPG1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/AutoRPG1.0.0/ && $(COPY_FILE) --parents autorpg.h newcharacter.h character.h namegenerator.h game.h item.h creature.h eventsgenerator.h .tmp/AutoRPG1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/AutoRPG1.0.0/ && $(COPY_FILE) --parents main.cpp autorpg.cpp newcharacter.cpp character.cpp namegenerator.cpp game.cpp item.cpp creature.cpp eventsgenerator.cpp .tmp/AutoRPG1.0.0/ && $(COPY_FILE) --parents autorpg.ui newcharacter.ui .tmp/AutoRPG1.0.0/ && (cd `dirname .tmp/AutoRPG1.0.0` && $(TAR) AutoRPG1.0.0.tar AutoRPG1.0.0 && $(COMPRESS) AutoRPG1.0.0.tar) && $(MOVE) `dirname .tmp/AutoRPG1.0.0`/AutoRPG1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/AutoRPG1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_autorpg.cpp moc_newcharacter.cpp moc_game.cpp moc_eventsgenerator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_autorpg.cpp moc_newcharacter.cpp moc_game.cpp moc_eventsgenerator.cpp
moc_autorpg.cpp: newcharacter.h \
		character.h \
		creature.h \
		namegenerator.h \
		item.h \
		game.h \
		eventsgenerator.h \
		autorpg.h
	/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) autorpg.h -o moc_autorpg.cpp

moc_newcharacter.cpp: character.h \
		creature.h \
		namegenerator.h \
		item.h \
		newcharacter.h
	/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) newcharacter.h -o moc_newcharacter.cpp

moc_game.cpp: character.h \
		creature.h \
		namegenerator.h \
		item.h \
		eventsgenerator.h \
		game.h
	/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) game.h -o moc_game.cpp

moc_eventsgenerator.cpp: character.h \
		creature.h \
		namegenerator.h \
		item.h \
		eventsgenerator.h
	/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) eventsgenerator.h -o moc_eventsgenerator.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		resources/rpg_bg.jpg
	/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_autorpg.h ui_newcharacter.h
compiler_uic_clean:
	-$(DEL_FILE) ui_autorpg.h ui_newcharacter.h
ui_autorpg.h: autorpg.ui
	/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic autorpg.ui -o ui_autorpg.h

ui_newcharacter.h: newcharacter.ui
	/home/sintell/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic newcharacter.ui -o ui_newcharacter.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp autorpg.h \
		newcharacter.h \
		character.h \
		creature.h \
		namegenerator.h \
		item.h \
		game.h \
		eventsgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

autorpg.o: autorpg.cpp autorpg.h \
		newcharacter.h \
		character.h \
		creature.h \
		namegenerator.h \
		item.h \
		game.h \
		eventsgenerator.h \
		ui_autorpg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autorpg.o autorpg.cpp

newcharacter.o: newcharacter.cpp newcharacter.h \
		character.h \
		creature.h \
		namegenerator.h \
		item.h \
		ui_newcharacter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newcharacter.o newcharacter.cpp

character.o: character.cpp character.h \
		creature.h \
		namegenerator.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character.o character.cpp

namegenerator.o: namegenerator.cpp namegenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o namegenerator.o namegenerator.cpp

game.o: game.cpp game.h \
		character.h \
		creature.h \
		namegenerator.h \
		item.h \
		eventsgenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

item.o: item.cpp item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

creature.o: creature.cpp creature.h \
		namegenerator.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creature.o creature.cpp

eventsgenerator.o: eventsgenerator.cpp eventsgenerator.h \
		character.h \
		creature.h \
		namegenerator.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventsgenerator.o eventsgenerator.cpp

moc_autorpg.o: moc_autorpg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autorpg.o moc_autorpg.cpp

moc_newcharacter.o: moc_newcharacter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newcharacter.o moc_newcharacter.cpp

moc_game.o: moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game.o moc_game.cpp

moc_eventsgenerator.o: moc_eventsgenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventsgenerator.o moc_eventsgenerator.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

